#!/usr/bin/env zsh
# mac_ide_setup.sh
# Sets up a fresh Mac user account for Concentrate.ai development.
# Safe to run on accounts with no prior configuration.
# If .zshrc already exists, this script will exit without modifying it.
# Requires: curl, zsh (default on all modern Macs)

echo ""
echo "🍎 Concentrate.ai Mac IDE Setup"
echo "================================"
echo ""
echo "This script will:"
echo "  • Create or update ~/.secrets with your Concentrate and BlueLobster API keys"
echo "  • Create ~/.zshrc (only if one does not already exist)"
echo "  • Install Homebrew (if not present)"
echo "  • Install jq (required for launcher)"
echo "  • Generate an RSA SSH key (if not present)"
echo "  • Add the SSH key to your Mac keychain"
echo "  • Create ~/scripts/concentrate.sh (BlueLobster VM manager)"
echo "  • Create ~/scripts/ and ~/dev_projects/ directories"
echo ""
echo "⚠️  This script is designed for a FRESH Mac user account."
echo "    If you have existing configuration you want to keep, exit now"
echo "    and configure manually using mac_ide_setup.md."
echo ""
read "proceed?  Continue? (y/n): "
[[ "$proceed" != "y" ]] && echo "Exiting." && exit 0
echo ""


# ── 1. Check for existing .zshrc ─────────────────────────────────────────────
if [[ -f "$HOME/.zshrc" ]]; then
  echo "⚠️  ~/.zshrc already exists."
  echo "    This script will NOT modify it — modifying an existing .zshrc"
  echo "    can break your terminal environment."
  echo ""
  echo "    Options:"
  echo "      • Exit and configure manually using mac_ide_setup.md"
  echo "      • Or create a fresh Mac user account and run this script there"
  echo ""
  echo "Exiting without changes."
  exit 1
fi


# ── 2. Handle .secrets ───────────────────────────────────────────────────────
echo "🔑 Setting up ~/.secrets..."
echo ""

if [[ -f "$HOME/.secrets" ]]; then
  if grep -q "CONCENTRATE_API_KEY" "$HOME/.secrets"; then
    echo "⚠️  CONCENTRATE_API_KEY already exists in ~/.secrets."
    echo "    Not overwriting. If you need to update your key, edit ~/.secrets manually."
    echo ""
  else
    echo "    ~/.secrets exists but does not contain CONCENTRATE_API_KEY."
    echo "    Appending safely."
    read "apikey?  Enter your Concentrate API key (starts with sk-cn-v1-): "
    echo "" >> "$HOME/.secrets"
    echo "# Concentrate.ai" >> "$HOME/.secrets"
    echo "export CONCENTRATE_API_KEY=\"$apikey\"" >> "$HOME/.secrets"
    echo "✅ CONCENTRATE_API_KEY appended to ~/.secrets"
    echo ""
  fi
else
  read "apikey?  Enter your Concentrate API key (starts with sk-cn-v1-): "
  cat > "$HOME/.secrets" << EOF
# ~/.secrets
# API keys — never commit this file to Git
# Last updated: $(date +%Y-%m-%d)

# Concentrate.ai
export CONCENTRATE_API_KEY="$apikey"
EOF
  echo "✅ ~/.secrets created"
  echo ""
fi

# ── 3. Handle BL API key in .secrets ─────────────────────────────────────────
echo "🦞 Setting up BlueLobster API key..."
echo ""

if grep -q "BLUE_LOBSTER_API_KEY" "$HOME/.secrets" 2>/dev/null; then
  echo "⚠️  BLUE_LOBSTER_API_KEY already exists in ~/.secrets."
  echo "    Not overwriting. Edit ~/.secrets manually if you need to update it."
  echo ""
else
  read "blkey?  Enter your BlueLobster API key: "
  echo "" >> "$HOME/.secrets"
  echo "# BlueLobster" >> "$HOME/.secrets"
  echo "export BLUE_LOBSTER_API_KEY=\"$blkey\"" >> "$HOME/.secrets"
  echo "✅ BLUE_LOBSTER_API_KEY added to ~/.secrets"
  echo ""
fi


# ── 4. Create .zshrc ─────────────────────────────────────────────────────────
echo "📝 Creating ~/.zshrc..."

cat > "$HOME/.zshrc" << 'EOF'
# ~/.zshrc
# Concentrate.ai standard Mac shell configuration
# Generated by mac_ide_setup.sh

# Prevent concentrate.sh from auto-launching in child terminal windows
# (set by concentrate.sh before opening a new window)
[[ "$LAUNCHER_CHILD" == "1" ]] && return

# Load SSH key into agent (silent — only prompts once ever)
ssh-add --apple-use-keychain ~/.ssh/id_rsa 2>/dev/null

# Load API keys
source ~/.secrets

# ── Aliases ──────────────────────────────────────────────────────────────────
alias myconfig="cat ~/.zshrc"
alias mykeys="printenv | grep -E '(API_KEY|BASE_URL|MODEL)'"
alias concentrate='~/scripts/concentrate.sh'

# ── Claude Code — route to Concentrate ───────────────────────────────────────
export ANTHROPIC_AUTH_TOKEN="$CONCENTRATE_API_KEY"
export ANTHROPIC_BASE_URL="https://api.concentrate.ai"
export ANTHROPIC_DEFAULT_OPUS_MODEL="minimax-m2-7-highspeed"
export ANTHROPIC_MODEL="opus"

# ── Land in working directory ─────────────────────────────────────────────────
cd ~/dev_projects 2>/dev/null || true

# ── Auto-launch VM manager on login ──────────────────────────────────────────
if [[ $SHLVL -eq 1 && -o login ]]; then
  ~/scripts/concentrate.sh
fi
EOF

echo "✅ ~/.zshrc created"
echo ""


# ── 5. Install Homebrew ───────────────────────────────────────────────────────
echo "🍺 Checking for Homebrew..."
if command -v brew &>/dev/null; then
  echo "✅ Homebrew already installed"
else
  echo "    Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  # Add brew to PATH for Apple Silicon Macs
  if [[ -f "/opt/homebrew/bin/brew" ]]; then
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> "$HOME/.zshrc"
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
  echo "✅ Homebrew installed"
fi
echo ""


# ── 6. Install jq ────────────────────────────────────────────────────────────
echo "🔧 Checking for jq..."
if command -v jq &>/dev/null; then
  echo "✅ jq already installed"
else
  brew install jq
  echo "✅ jq installed"
fi
echo ""


# ── 7. Generate SSH key ───────────────────────────────────────────────────────
echo "🔐 Checking for SSH key..."
if [[ -f "$HOME/.ssh/id_rsa" ]]; then
  echo "✅ SSH key already exists at ~/.ssh/id_rsa"
else
  echo "    Generating RSA SSH key..."
  echo "    Note: BlueLobster requires RSA — Ed25519 is not supported."
  echo ""
  read "ssh_email?  Enter your email address for the SSH key: "
  ssh-keygen -t rsa -b 4096 -C "$ssh_email" -f "$HOME/.ssh/id_rsa"
  echo ""
  echo "✅ SSH key generated"
fi
echo ""


# ── 8. Add SSH key to Mac keychain ────────────────────────────────────────────
echo "🔑 Adding SSH key to Mac keychain..."
ssh-add --apple-use-keychain "$HOME/.ssh/id_rsa" 2>/dev/null
echo "✅ SSH key added to keychain (passphrase stored — won't be asked again)"
echo ""


# ── 9. Create directories ─────────────────────────────────────────────────────
echo "📁 Creating ~/scripts and ~/dev_projects..."
mkdir -p "$HOME/scripts"
mkdir -p "$HOME/dev_projects"
echo "✅ Directories ready"
echo ""


# ── 10. Write concentrate.sh ───────────────────────────────────────────────────
echo "🦞 Writing ~/scripts/concentrate.sh..."

cat > "$HOME/scripts/concentrate.sh" << 'CONCENTRATE_EOF'
#!/usr/bin/env zsh
# concentrate.sh
# BlueLobster VM manager — interactive event-loop app.
# Shows all VMs with status. Per-VM sub-menu: Connect, Git Sync, Shut Down.
# Connect opens a new terminal window for SSH + Zed, leaving this menu live.
# Requires: jq, BLUE_LOBSTER_API_KEY in environment

BL_API="https://api.bluelobster.ai"

# ── Zed check (one-time on first run) ────────────────────────────────────────
if ! command -v zed &>/dev/null; then
  echo ""
  echo "⚠️  Zed is not installed."
  echo "    Zed is the recommended IDE for Concentrate.ai development."
  echo ""
  read "installzed?  Install Zed now via Homebrew? (y/n): "
  echo ""
  if [[ "$installzed" == "y" ]]; then
    echo "🍺 Installing Zed..."
    brew install --cask zed
    echo ""
    export PATH="$HOME/.local/bin:$PATH"
    if ! command -v zed &>/dev/null; then
      echo "⚠️  Zed installed but CLI not found in PATH yet."
      echo "    Open a new terminal window and run: concentrate"
      exit 0
    else
      echo "✅ Zed installed."
    fi
  else
    echo "   Skipping Zed install. You can install it later with:"
    echo "     brew install --cask zed"
    echo "   The VM manager will work but Connect will not open Zed automatically."
  fi
  echo ""
fi

# ── BL API key check ──────────────────────────────────────────────────────────
if [[ -z "$BLUE_LOBSTER_API_KEY" ]]; then
  echo ""
  echo "❌ BLUE_LOBSTER_API_KEY is not set."
  echo "   Add it to ~/.secrets and run: source ~/.zshrc"
  echo ""
  exit 1
fi

# ── Helper: fetch all instances ───────────────────────────────────────────────
# Populates global arrays: names, ips, pstatuses, usernames, uuids, count
fetch_instances() {
  local raw
  raw=$(curl -sf \
    -H "X-API-Key: $BLUE_LOBSTER_API_KEY" \
    "$BL_API/api/v1/instances") || {
    echo "❌ Could not reach BlueLobster API. Check your key or network."
    return 1
  }
  names=(${(f)"$(echo "$raw" | jq -r '.[].name')"})
  ips=(${(f)"$(echo "$raw" | jq -r '.[].ip_address')"})
  pstatuses=(${(f)"$(echo "$raw" | jq -r '.[].power_status')"})
  usernames=(${(f)"$(echo "$raw" | jq -r '.[].vm_username')"})
  uuids=(${(f)"$(echo "$raw" | jq -r '.[].uuid')"})
  count=${#names[@]}
}

# ── Helper: refresh status for a single VM by index ──────────────────────────
refresh_one() {
  local idx=$1
  local uuid="${uuids[$idx]}"
  local raw
  raw=$(curl -sf \
    -H "X-API-Key: $BLUE_LOBSTER_API_KEY" \
    "$BL_API/api/v1/instances/$uuid") || return 1
  pstatuses[$idx]=$(echo "$raw" | jq -r '.power_status')
  ips[$idx]=$(echo "$raw" | jq -r '.ip_address')
}

# ── Helper: power on a VM and poll until running ──────────────────────────────
power_on() {
  local idx=$1
  local name="${names[$idx]}"
  local uuid="${uuids[$idx]}"

  echo "⚡ Sending power-on request for $name..."
  curl -sf -X POST \
    -H "X-API-Key: $BLUE_LOBSTER_API_KEY" \
    "$BL_API/api/v1/instances/$uuid/power-on" > /dev/null || {
    echo "❌ Power-on request failed."
    return 1
  }

  echo "⏳ Waiting for $name to start..."
  for attempt in {1..24}; do
    sleep 5
    refresh_one $idx
    if [[ "${pstatuses[$idx]}" == "running" ]]; then
      echo "✅ $name is running."
      return 0
    fi
    echo "   still ${pstatuses[$idx]}... ($attempt/24)"
  done
  echo "❌ Timed out. Try again in a moment."
  return 1
}

# ── Helper: git pull + push on VM over SSH (no interactive shell) ─────────────
git_sync_vm() {
  local user=$1
  local ip=$2
  local name=$3
  echo ""
  echo "🔄 Git Sync — $name"
  echo ""
  echo "   Pulling latest from remote..."
  ssh -o ConnectTimeout=10 "$user@$ip" \
    "cd ~/dev_projects && git pull --quiet" 2>&1 | sed 's/^/   /'
  echo ""
  read "dopush?  Push local commits to remote? (y/n): "
  if [[ "$dopush" == "y" ]]; then
    ssh -o ConnectTimeout=10 "$user@$ip" \
      "cd ~/dev_projects && git push" 2>&1 | sed 's/^/   /'
    echo "   ✅ Push complete."
  else
    echo "   Skipped push."
  fi
  echo ""
}

# ── Helper: shut down a VM (with optional git sync first) ─────────────────────
shutdown_vm() {
  local idx=$1
  local name="${names[$idx]}"
  local uuid="${uuids[$idx]}"
  local user="${usernames[$idx]}"
  local ip="${ips[$idx]}"

  echo ""
  if [[ "${pstatuses[$idx]}" != "running" ]]; then
    echo "   $name is already ${pstatuses[$idx]}. Nothing to do."
    echo ""
    return 0
  fi

  read "dosync?  Git Sync before shutting down? (y/n): "
  if [[ "$dosync" == "y" ]]; then
    git_sync_vm "$user" "$ip" "$name"
  fi

  echo "   Sending shutdown request for $name..."
  curl -sf -X POST \
    -H "X-API-Key: $BLUE_LOBSTER_API_KEY" \
    "$BL_API/api/v1/instances/$uuid/shutdown" > /dev/null || {
    echo "❌ Shutdown request failed. Use the BlueLobster dashboard."
    return 1
  }
  pstatuses[$idx]="stopped"
  echo "✅ Shutdown queued. $name will stop shortly."
  echo ""
}

# ── Helper: print the main menu ───────────────────────────────────────────────
print_main_menu() {
  clear
  echo ""
  echo "  🦞 BlueLobster VM Manager"
  echo "  ─────────────────────────────────────────────"
  echo ""
  if [[ $count -eq 0 ]]; then
    echo "  No VMs found on your account."
  else
    for i in {1..$count}; do
      local icon="🔴"
      [[ "${pstatuses[$i]}" == "running" ]] && icon="🟢"
      printf "  %s)  %-22s %s %-10s  %s\n" \
        "$i" "${names[$i]}" "$icon" "${pstatuses[$i]}" "${ips[$i]}"
    done
  fi
  echo ""
  echo "  r)  Refresh"
  echo "  q)  Quit"
  echo ""
}

# ── Helper: print sub-menu for a selected VM ──────────────────────────────────
print_vm_menu() {
  local idx=$1
  local icon="🔴"
  [[ "${pstatuses[$idx]}" == "running" ]] && icon="🟢"

  clear
  echo ""
  echo "  🦞 $icon  ${names[$idx]}  (${pstatuses[$idx]})"
  echo "  ─────────────────────────────────────────────"
  echo ""
  echo "  1)  Connect        (open SSH + Zed in new window)"
  echo "  2)  Git Sync       (pull + push, no SSH change)"
  echo "  3)  Shut Down      (optional git sync, then power off)"
  echo ""
  echo "  b)  Back"
  echo ""
}

# ── Main event loop ───────────────────────────────────────────────────────────
echo ""
echo "   Fetching your BlueLobster VMs..."
fetch_instances || exit 1

while true; do
  print_main_menu
  read "main_choice?  Enter number, r, or q: "
  echo ""

  # Quit
  if [[ "$main_choice" == "q" ]]; then
    local running_names=()
    for i in {1..$count}; do
      [[ "${pstatuses[$i]}" == "running" ]] && running_names+=("${names[$i]}")
    done
    if [[ ${#running_names[@]} -gt 0 ]]; then
      echo "  ⚠️  These VMs are still running:"
      for n in $running_names; do echo "      • $n"; done
      echo ""
      read "force_quit?  Quit anyway without shutting them down? (y/n): "
      echo ""
      [[ "$force_quit" != "y" ]] && continue
    fi
    echo "  👋 Goodbye."
    echo ""
    break
  fi

  # Refresh
  if [[ "$main_choice" == "r" ]]; then
    echo "   Refreshing..."
    fetch_instances || true
    continue
  fi

  # VM selection — validate input
  if ! [[ "$main_choice" =~ ^[0-9]+$ ]] || \
     (( main_choice < 1 || main_choice > count )); then
    echo "  ❌ Invalid choice. Press enter to continue."
    read
    continue
  fi

  sel=$main_choice

  # VM sub-menu loop
  while true; do
    print_vm_menu $sel
    read "vm_choice?  Enter 1, 2, 3, or b: "
    echo ""

    case "$vm_choice" in

      1) # Connect ─────────────────────────────────────────────────────────────
        local name="${names[$sel]}"
        local ip="${ips[$sel]}"
        local user="${usernames[$sel]}"
        local pstatus="${pstatuses[$sel]}"

        if [[ "$pstatus" != "running" ]]; then
          power_on $sel || { read; break; }
          ip="${ips[$sel]}"
        fi

        echo "  🚀 Opening new terminal window for $name..."
        # LAUNCHER_CHILD=1 tells .zshrc to skip auto-launching this app
        # Child terminal: git pulls on VM, opens Zed remote, drops into SSH
        # On SSH exit the child window closes itself (exit at end of script)
        osascript << APPLESCRIPT
tell application "Terminal"
  do script "export LAUNCHER_CHILD=1; \
    echo ''; \
    echo '🔗 Connecting to $name ($user@$ip)...'; \
    echo ''; \
    ssh -o ConnectTimeout=10 $user@$ip 'cd ~/dev_projects && git pull --quiet' 2>/dev/null && echo '   ✅ Git pull complete.'; \
    echo ''; \
    zed 'ssh://$user@$ip/home/$user/dev_projects' 2>/dev/null &; \
    ssh $user@$ip; \
    exit"
  activate
end tell
APPLESCRIPT
        echo "  ✅ Connection window opened."
        echo ""
        refresh_one $sel
        read "?  Press enter to return to menu."
        ;;

      2) # Git Sync ──────────────────────────────────────────────────────────
        if [[ "${pstatuses[$sel]}" != "running" ]]; then
          echo "  ❌ ${names[$sel]} is not running. Start it first with Connect."
          echo ""
          read
        else
          git_sync_vm "${usernames[$sel]}" "${ips[$sel]}" "${names[$sel]}"
          read "?  Press enter to continue."
        fi
        ;;

      3) # Shut Down ────────────────────────────────────────────────────────
        shutdown_vm $sel
        refresh_one $sel 2>/dev/null || pstatuses[$sel]="stopped"
        read "?  Press enter to continue."
        break  # return to main menu after shutdown
        ;;

      b|B)
        break
        ;;

      *)
        echo "  ❌ Invalid choice."
        read
        ;;
    esac
  done

done
CONCENTRATE_EOF

chmod +x "$HOME/scripts/concentrate.sh"
echo "✅ ~/scripts/concentrate.sh written and made executable"
echo ""


# ── 11. Write Zed settings.json ────────────────────────────────────────────────
echo "⚙️  Writing ~/.config/zed/settings.json..."
mkdir -p "$HOME/.config/zed"

if [[ -f "$HOME/.config/zed/settings.json" ]]; then
  echo "⚠️  ~/.config/zed/settings.json already exists. Skipping — not overwriting."
  echo "    To apply Concentrate defaults manually, see mac_ide_setup.md Section 6."
else
  cat > "$HOME/.config/zed/settings.json" << 'EOF'
{
  "session": {
    "trust_all_worktrees": true
  },
  "agent_servers": {
    "claude-acp": {
      "type": "registry"
    }
  },
  "agent": {
    "default_profile": "minimal",
    "default_model": {
      "provider": "openai",
      "model": "minimax-m2-7-highspeed"
    },
    "dock": "right"
  },
  "language_models": {
    "openai_compatible": {
      "Concentrate": {
        "api_url": "https://api.concentrate.ai",
        "available_models": [
          {
            "name": "minimax-m2-7-highspeed",
            "display_name": "MiniMax M2 (Concentrate)",
            "max_tokens": 128000
          },
          {
            "name": "claude-sonnet-4-6",
            "display_name": "Claude Sonnet 4.6 (Concentrate)",
            "max_tokens": 16000
          }
        ]
      }
    }
  },
  "project_panel": {
    "dock": "left"
  },
  "outline_panel": {
    "dock": "left"
  },
  "collaboration_panel": {
    "dock": "left"
  },
  "git_panel": {
    "dock": "left"
  },
  "icon_theme": {
    "mode": "dark",
    "light": "Zed (Default)",
    "dark": "Zed (Default)"
  },
  "telemetry": {
    "diagnostics": true,
    "metrics": false
  },
  "ui_font_size": 16,
  "buffer_font_size": 15,
  "theme": {
    "mode": "dark",
    "light": "One Light",
    "dark": "One Dark"
  }
}
EOF
  echo "✅ ~/.config/zed/settings.json written"
fi
echo ""


# ── Done ──────────────────────────────────────────────────────────────────────
echo "================================"
echo "✅ Mac setup complete."
echo ""
echo "⚠️  IMPORTANT: Do not close and reopen your terminal."
echo "    Run this command right now to activate your new configuration:"
echo ""
echo "      source ~/.zshrc"
echo ""
echo "Next steps:"
echo "  1. Run: source ~/.zshrc"
echo "  2. Add your SSH public key to your BlueLobster VM:"
echo "     cat ~/.ssh/id_rsa.pub"
echo "     (paste this into your VM's authorized_keys or BlueLobster dashboard)"
echo "  3. Add your BLUE_LOBSTER_API_KEY to ~/.secrets to use the launcher"
echo "  4. Open Zed and complete AI setup — see mac_ide_setup.md Section 6"
echo "  5. Run: concentrate"
echo ""

